name: context-cvss
repository: github.com/quentinkhoo/trivy-plugin-context-cvss
version: "0.1.4"
maintainer: quentinkhoo
summary: Recalculate vulnerability scores with environmental and temporal metrics
description: |-
  A trivy plugin that recalculates vulnerability scores by including environmental and temporal metrics
output: true
platforms:
  - selector:
      os: darwin
      arch: amd64
    uri: https://github.com/quentinkhoo/trivy-plugin-context-cvss/releases/download/v0.1.4/trivy_plugin_context_cvss_0.1.4_darwin-amd64.tar.gz
    bin: ./context-cvss
  - selector:
      os: darwin
      arch: arm64
    uri: https://github.com/quentinkhoo/trivy-plugin-context-cvss/releases/download/v0.1.4/trivy_plugin_context_cvss_0.1.4_darwin-arm64.tar.gz
    bin: ./context-cvss
  - selector:
      os: linux
      arch: amd64
    uri: https://github.com/quentinkhoo/trivy-plugin-context-cvss/releases/download/v0.1.4/trivy_plugin_context_cvss_0.1.4_linux-amd64.tar.gz
    bin: ./context-cvss
  - selector:
      os: linux
      arch: arm64
    uri: https://github.com/quentinkhoo/trivy-plugin-context-cvss/releases/download/v0.1.4/trivy_plugin_context_cvss_0.1.4_linux-arm64.tar.gz
    bin: ./context-cvss